// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Link-Kratos/internal/biz"
	"Link-Kratos/internal/conf"
	"Link-Kratos/internal/data"
	"Link-Kratos/internal/server"
	"Link-Kratos/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	realTimeTrafficRepo := data.NewRealTimeTrafficRepo(dataData, logger)
	interceptorRepo := data.NewInterceptorRepo(dataData, logger)
	statisticsRepo := data.NewStatisticsRepo(dataData, logger)
	trafficUsecase := biz.NewTrafficUsecase(realTimeTrafficRepo, interceptorRepo, statisticsRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	profileRepo := data.NewProfileRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, profileRepo, logger, jwt)
	linkService := service.NewLinkService(trafficUsecase, userUsecase)
	grpcServer := server.NewGRPCServer(confServer, linkService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, linkService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
