server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    dsn: "root:65552588@tcp(127.0.0.1:3306)/Link_Kratos?charset=utf8mb4&parseTime=True&loc=Local"
jwt:
  secret: "hello"