// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: link/v1/link.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Link_Interceptor_FullMethodName     = "/link.v1.Link/Interceptor"
	Link_Statistics_FullMethodName      = "/link.v1.Link/Statistics"
	Link_RealTimeTraffic_FullMethodName = "/link.v1.Link/RealTimeTraffic"
)

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkClient interface {
	// 拦截流量信息，并返回
	Interceptor(ctx context.Context, in *InterceptorRequest, opts ...grpc.CallOption) (*InterceptorReply, error)
	// 统计流量信息，并返回
	Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsReply, error)
	// 获取实时流量信息，并返回
	RealTimeTraffic(ctx context.Context, in *RealTimeTrafficRequest, opts ...grpc.CallOption) (*RealTimeTrafficReply, error)
}

type linkClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkClient(cc grpc.ClientConnInterface) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Interceptor(ctx context.Context, in *InterceptorRequest, opts ...grpc.CallOption) (*InterceptorReply, error) {
	out := new(InterceptorReply)
	err := c.cc.Invoke(ctx, Link_Interceptor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsReply, error) {
	out := new(StatisticsReply)
	err := c.cc.Invoke(ctx, Link_Statistics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) RealTimeTraffic(ctx context.Context, in *RealTimeTrafficRequest, opts ...grpc.CallOption) (*RealTimeTrafficReply, error) {
	out := new(RealTimeTrafficReply)
	err := c.cc.Invoke(ctx, Link_RealTimeTraffic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
// All implementations must embed UnimplementedLinkServer
// for forward compatibility
type LinkServer interface {
	// 拦截流量信息，并返回
	Interceptor(context.Context, *InterceptorRequest) (*InterceptorReply, error)
	// 统计流量信息，并返回
	Statistics(context.Context, *StatisticsRequest) (*StatisticsReply, error)
	// 获取实时流量信息，并返回
	RealTimeTraffic(context.Context, *RealTimeTrafficRequest) (*RealTimeTrafficReply, error)
	mustEmbedUnimplementedLinkServer()
}

// UnimplementedLinkServer must be embedded to have forward compatible implementations.
type UnimplementedLinkServer struct {
}

func (UnimplementedLinkServer) Interceptor(context.Context, *InterceptorRequest) (*InterceptorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Interceptor not implemented")
}
func (UnimplementedLinkServer) Statistics(context.Context, *StatisticsRequest) (*StatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Statistics not implemented")
}
func (UnimplementedLinkServer) RealTimeTraffic(context.Context, *RealTimeTrafficRequest) (*RealTimeTrafficReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealTimeTraffic not implemented")
}
func (UnimplementedLinkServer) mustEmbedUnimplementedLinkServer() {}

// UnsafeLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServer will
// result in compilation errors.
type UnsafeLinkServer interface {
	mustEmbedUnimplementedLinkServer()
}

func RegisterLinkServer(s grpc.ServiceRegistrar, srv LinkServer) {
	s.RegisterService(&Link_ServiceDesc, srv)
}

func _Link_Interceptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterceptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Interceptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Link_Interceptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Interceptor(ctx, req.(*InterceptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Statistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Statistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Link_Statistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Statistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_RealTimeTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealTimeTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).RealTimeTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Link_RealTimeTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).RealTimeTraffic(ctx, req.(*RealTimeTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Link_ServiceDesc is the grpc.ServiceDesc for Link service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Link_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "link.v1.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Interceptor",
			Handler:    _Link_Interceptor_Handler,
		},
		{
			MethodName: "Statistics",
			Handler:    _Link_Statistics_Handler,
		},
		{
			MethodName: "RealTimeTraffic",
			Handler:    _Link_RealTimeTraffic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link/v1/link.proto",
}
